In [4]:
import pandas as pd

In [7]:
df4=pd.read_csv('../input/H1B_FY_2014.csv',delimiter=';')
df5=pd.read_csv('../input/H1B_FY_2015.csv',delimiter=';')
df6=pd.read_csv('../input/H1B_FY_2016.csv',delimiter=';')

/home/kshitij/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3018: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [16]:
df4.columns

Index(['Unnamed: 0', 'LCA_CASE_NUMBER', 'STATUS', 'LCA_CASE_SUBMIT',
       'DECISION_DATE', 'VISA_CLASS', 'LCA_CASE_EMPLOYMENT_START_DATE',
       'LCA_CASE_EMPLOYMENT_END_DATE', 'LCA_CASE_EMPLOYER_NAME',
       'LCA_CASE_EMPLOYER_ADDRESS', 'LCA_CASE_EMPLOYER_CITY',
       'LCA_CASE_EMPLOYER_STATE', 'LCA_CASE_EMPLOYER_POSTAL_CODE',
       'LCA_CASE_SOC_CODE', 'LCA_CASE_SOC_NAME', 'LCA_CASE_JOB_TITLE',
       'LCA_CASE_WAGE_RATE_FROM', 'LCA_CASE_WAGE_RATE_TO',
       'LCA_CASE_WAGE_RATE_UNIT', 'FULL_TIME_POS', 'TOTAL_WORKERS',
       'LCA_CASE_WORKLOC1_CITY', 'LCA_CASE_WORKLOC1_STATE', 'PW_1',
       'PW_UNIT_1', 'PW_SOURCE_1', 'OTHER_WAGE_SOURCE_1', 'YR_SOURCE_PUB_1',
       'LCA_CASE_WORKLOC2_CITY', 'LCA_CASE_WORKLOC2_STATE', 'PW_2',
       'PW_UNIT_2', 'PW_SOURCE_2', 'OTHER_WAGE_SOURCE_2', 'YR_SOURCE_PUB_2',
       'LCA_CASE_NAICS_CODE'],
      dtype='object')

In [15]:
asd = df6.columns[2]
asd.lower().endswith("status")

True

In [17]:
df4.head()

,Unnamed: 0,LCA_CASE_NUMBER,STATUS,LCA_CASE_SUBMIT,DECISION_DATE,VISA_CLASS,LCA_CASE_EMPLOYMENT_START_DATE,LCA_CASE_EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_NAME,LCA_CASE_EMPLOYER_ADDRESS,...,OTHER_WAGE_SOURCE_1,YR_SOURCE_PUB_1,LCA_CASE_WORKLOC2_CITY,LCA_CASE_WORKLOC2_STATE,PW_2,PW_UNIT_2,PW_SOURCE_2,OTHER_WAGE_SOURCE_2,YR_SOURCE_PUB_2,LCA_CASE_NAICS_CODE
0,0,I-200-09106-546545,CERTIFIED-WITHDRAWN,2013-01-18 18:05:43,2014-09-29 15:59:50,H-1B,2013-02-01 00:00:00,2016-02-01 00:00:00,TEXAS STATE UNIVERSITY-SAN MARCOS,601 UNIVERSITY DRIVE,...,OFLC ONLINE DATA CENTER,2013.0,ST. LOUIS,MO,49566.0,Year,OES,OFLC ONLINE DATA CENTER,OFLC ONLINE DATA CENTER,611310.0
1,1,I-200-09162-143337,CERTIFIED,2014-03-17 11:11:45,2014-03-21 23:11:51,H-1B,2014-09-15 00:00:00,2017-09-15 00:00:00,"EYE SPECIALISTS OF INDIANA, P.C.",1901 N. MERIDIAN ST.,...,OFLC ONLINE DATA CENTER,2013.0,INDIANAPOLIS,IN,64251.0,Year,Other,OFLC ONLINE DATA CENTER,OFLC ONLINE DATA CENTER,621320.0
2,2,I-200-09182-550211,DENIED,2014-03-14 17:05:01,2014-03-20 16:59:49,H-1B,2014-04-01 00:00:00,2015-04-01 00:00:00,"LHB, INC.",21 WEST SUPERIOR STREET,...,OFLIC ONLINE,2014.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,541330.0
3,3,I-200-09193-873099,CERTIFIED,2014-03-01 12:37:02,2014-03-06 22:03:37,H-1B,2014-08-28 00:00:00,2017-08-27 00:00:00,"WAM USA, INC.",75 BOULDERBROOK CIRCLE,...,OFLC ONLINE DATA CENTER,2014.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,333922.0
4,4,I-200-09197-120609,CERTIFIED-WITHDRAWN,2014-03-10 15:33:41,2014-03-17 10:52:46,H-1B,2014-09-01 00:00:00,2017-09-01 00:00:00,"DFUSE TECHNOLOGIES, INC.",20143 DESERT FOREST DRIVE,...,OFLC ONLINE DATA CENTER,2013.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,541519.0

In [28]:
print("%s;%d;%3.1f%%\n"%("Software",6,100*0.1/10))

Software;6;1.0%

In [43]:
import sys

# Read Input file
with open('../input/trial.csv','r') as file:
    data = file.read()
    records = data.split('\n')

# Obtain header from the data
    header = records[0].split(';')


# Required Information for the problem: -
# Occupation name as per SOC and corresponding number of certified applications
# Total number of certified applications
# State for work place and corresponding number of certified applications


# It has been mentioned that data can have different columns. So, the required information
# will be parsed after determining the position of column in data file
# Find the column number corresponding to required information
    for i in range(len(header)):
# Find the column corresponding to status
        if "status" in header[i].lower(): 
            status_col = i
# Find the column corresponding to occupation name
        elif "soc_name" in header[i].lower(): 
            occupation_col = i
# For 2014 data file, there are 2 work locations which will have to be counted for both locations
        state_cols = []
        elif (("worksite_state" in header[i].lower()):
              
              
              
              
              
              # || (("workloc" in header[i].lower()) && ("state" in header[i].lower()))):
            state_cols.append(i)



# Store data in dictionaries
occupations = {}
total_certified_applications = 0
states = {}
for record in records:
    info = record.split(';')

# Check if this record belongs to a certified application
    if record[status_col]=='Certified':
        total_certified_applications += 1

# Store the counter in the occupations dictionary
        if record[occupation_col] in occupations:
            occupations[record[occupation_col]] += 1
        else:
            occupations[record[occupation_col]] = 1

# Store the counter in the states dictionary
        for col in state_cols:
            if record[col] in states:
                states[record[col]] += 1
            else:
                states[record[col]] = 1


# Counters have been stored for occupations and states

# Evaluate metrics for occupations
with open('./output.txt','w') as file:
    file.write("TOP_OCCUPATIONS;NUMBER_CERTIFIED_APPLICATIONS;PERCENTAGE\n")
    for key, value in sorted(occupations.iteritems(), key=lambda (k,v): (v,k),reverse=True):
        file.write("%s;%d;%3.1f%%\n"%(key,value,100*value/total_certified_applications))

SyntaxError: invalid syntax (<ipython-input-43-bfda8bca0442>, line 30)